import 'package:flutter/material.dart';
import 'package:vetcare_connect/utils/app_currency.dart';

/// Explicit unavailable state, not a payment gateway or proof of payment.
class QrCheckoutSheet extends StatelessWidget {
  final String method;
  final double total;

  const QrCheckoutSheet({
    super.key,
    required this.method,
    required this.total,
  });

  /// Always returns null: dismissing this sheet cannot confirm payment.
  static Future<String?> show(
    BuildContext context, {
    required String method,
    required double total,
  }) async {
    await showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      builder: (sheetContext) => SafeArea(
        child: Padding(
          padding: EdgeInsets.fromLTRB(
            20,
            20,
            20,
            20 + MediaQuery.of(sheetContext).viewInsets.bottom,
          ),
          child: QrCheckoutSheet(method: method, total: total),
        ),
      ),
    );
    return null;
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          const Icon(Icons.info_outline, size: 32),
          const SizedBox(height: 12),
          Text('Online payments not configured',
              style: Theme.of(context).textTheme.titleLarge),
          const SizedBox(height: 12),
          Text(
              '$method is currently unavailable. No payment has been collected or confirmed.'),
          const SizedBox(height: 12),
          if (total.isFinite && total > 0)
            Text('Order total: ${AppCurrency.peso(total)}'),
          const SizedBox(height: 12),
          const Text(
            'Please choose pay at clinic. Online payment will be available only '
            'after the clinic connects an approved payment provider. '
            'Do not transfer money using a reference generated by this app.',
          ),
          const SizedBox(height: 20),
          OutlinedButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }
}
